### ISSUE TITLE
`ResolveClaim` should default to 100% and give an option for 50%, not allow arbitrary percentages

### ISSUE THREAD

**Issue by quinn-dougherty** [quinn-dougherty/rallypoint#57]

**Comment by woontoon** [comment]
why not? isnt it good that users will be able to pay bounties out in ways other than 50/50 between just two claims?

**Comment by quinn-dougherty** [comment]
> why not?

I think it would be a failure mode if people started doing 80 and 90% a lot--- the claimant would feel burned out, and there wouldn't be very much left in escrow. we should target escrow getting emptied as much as we can, and fine grained control works against this. So I think we need to nudge to 100%, secondary nudge to 50%, then maybe unlock a slider if the user _really_ wants it. 

Discussing this with a [test user](https://github.com/quinn-dougherty/rallypoint/discussions/58#discussioncomment-8434676), a slider that only has increments of 10 is a compelling option as well.

**Comment by buddy-web3** [comment]
PR: https://github.com/quinn-dougherty/rallypoint/pull/64
